[package]
name = "dotnet-rs"
version = "0.1.0"
authors = ["Psilon <pzixel@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
goblin = {git = "https://github.com/m4b/goblin.git"}
scroll = "0.9.2"

[profile.release]
lto = true
